name: Run Selenium Scraper

on:
  schedule:
    - cron: '0 13 * * *' # Runs every day at 3pm.
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo mkdir -p /etc/apt/sources.list.d
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get -y install google-chrome-stable
    - name: Install ChromeDriver
      run: |
        # Using specific ChromeDriver version for Chrome I used 132
        CHROMEDRIVER_VERSION="144.0.7559.59"
        echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        chmod +x chromedriver-linux64/chromedriver
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: execute python script

      run: python script.py

    - name: Git commit
      run: |
          git add *.csv
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -m "Data commit"

    - name: Git push
      run: |
          git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
      env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
